[package]
name = "robot_brownian_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19.0"
clap = { version = "4.6.1", features = ["derive"] }
futures = "0.3.32"
r2r = "0.9.5"
rand = "0.10.1"
rand_chacha = "0.10.0"
rand_distr = "0.6.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "time", "sync"] }
